import re
from pathlib import Path

CATEGORIES = ['background', 'texture', 'color', 'object_part', 'scene', 'object']

# ---------------------------------------------------------------------------
# Tier 1: Explicit mapping for every item in clip_labeler's supplementary
# vocabularies (_PATCH_VOCAB + _TEXTURE_SCENE_VOCAB).
# These labels were purpose-designed to describe visual patch properties, so
# each one has an unambiguous category that we assign directly — no guessing.
# ---------------------------------------------------------------------------
_SUPP_MAP: dict[str, str] = {
    # --- _PATCH_VOCAB ---
    'green leaf':           'scene',        # vegetation / foliage background
    'animal fur':           'texture',
    'white fur':            'texture',
    'black fur':            'texture',
    'brown fur':            'texture',
    'metal surface':        'texture',
    'wooden surface':       'texture',
    'concrete surface':     'texture',
    'stone surface':        'texture',
    'grass texture':        'scene',        # grass is an environmental element
    'fabric texture':       'texture',
    'feather texture':      'texture',
    'scale texture':        'texture',
    'animal eye':           'object_part',
    'bird beak':            'object_part',
    'animal nose':          'object_part',
    'animal ear':           'object_part',
    'animal paw':           'object_part',
    'wheel':                'object_part',
    'window':               'object_part',
    'roof tile':            'object_part',
    'brick wall':           'texture',      # architectural surface pattern
    'wooden grid':          'texture',
    'vertical stripe':      'texture',
    'horizontal stripe':    'texture',
    'diagonal line':        'texture',
    'circular pattern':     'texture',
    'dark background':      'background',
    'bright background':    'background',
    'blurred background':   'background',
    'water surface':        'scene',
    'sandy surface':        'scene',
    'snow surface':         'scene',
    'wing':                 'object_part',
    'fin':                  'object_part',
    'tail':                 'object_part',
    'claw':                 'object_part',
    'face':                 'object_part',
    # --- _TEXTURE_SCENE_VOCAB ---
    'fur':                  'texture',
    'feather':              'texture',
    'scales':               'texture',
    'skin':                 'texture',
    'wool':                 'texture',
    'fabric':               'texture',
    'metal':                'texture',
    'wood':                 'texture',
    'stone':                'texture',
    'glass':                'texture',
    'plastic':              'texture',
    'brick':                'texture',
    'tile':                 'texture',
    'stripe':               'texture',
    'pattern':              'texture',
    'texture':              'texture',
    'edge':                 'texture',
    'dot':                  'texture',
    'grid':                 'texture',
    'gradient':             'texture',
    'shadow':               'background',   # lighting artefact, not content
    'background':           'background',
    'sky':                  'scene',
    'water':                'scene',
    'ocean':                'scene',
    'mountain':             'scene',
    'forest':               'scene',
    'desert':               'scene',
    'snow':                 'scene',
    'sand':                 'scene',
    'rock':                 'scene',
    'cloud':                'scene',
    'wall':                 'scene',
    'floor':                'scene',
    'road':                 'scene',
    'light':                'color',
    'dark':                 'color',
}


# ---------------------------------------------------------------------------
# Tier 2: ImageNet-1000 class names → always 'object'.
# All 1000 ImageNet classes are concrete objects or living things; none are
# purely textures, scenes, colors, or body parts at the class level.
# Compound names like "black bear" or "water buffalo" are animals and must
# not be matched by the color/scene keyword rules in Tier 3.
#
# Load priority:
#   1. torchvision (authoritative source, same list used by clip_labeler)
#   2. data/imagenet_classes.txt  (bundled fallback, generated by NB06 cell-0)
# ---------------------------------------------------------------------------
def _load_imagenet_classes() -> set[str]:
    try:
        from torchvision.models import ResNet50_Weights
        return {s.lower() for s in ResNet50_Weights.IMAGENET1K_V1.meta['categories']}
    except ImportError:
        pass
    txt = Path(__file__).parent.parent / 'data' / 'imagenet_classes.txt'
    if txt.exists():
        return {ln.strip().lower() for ln in txt.read_text(encoding='utf-8').splitlines() if ln.strip()}
    return set()


_IMAGENET_CLASSES: set[str] = _load_imagenet_classes()


# ---------------------------------------------------------------------------
# Tier 3: Keyword fallback.
# In practice this should never fire for labels produced by clip_labeler,
# because every label in the vocabulary is covered by Tier 1 or Tier 2.
# Retained as a safety net for ad-hoc calls with arbitrary label strings.
# ---------------------------------------------------------------------------
_FALLBACK_RULES: list[tuple[str, list[str]]] = [
    ('background',  ['background', 'backdrop']),
    ('object_part', ['eye', 'beak', 'nose', 'ear', 'paw', 'muzzle', 'wing', 'fin',
                     'tail', 'claw', 'wheel', 'window', 'roof', 'face',
                     'antenna', 'horn', 'tooth']),
    ('scene',       ['sky', 'water', 'ocean', 'mountain', 'forest', 'desert', 'snow',
                     'sand', 'rock', 'cloud', 'road', 'floor', 'grass', 'surface',
                     'field', 'beach', 'river', 'lake', 'soil', 'mud', 'wall']),
    ('texture',     ['fur', 'feather', 'scale', 'grain', 'fabric', 'skin', 'wool',
                     'brick', 'tile', 'stripe', 'pattern', 'texture', 'edge', 'dot', 'grid']),
    ('color',       ['white', 'black', 'brown', 'dark', 'bright']),
]
_FALLBACK_PATTERNS: list[tuple[str, list[re.Pattern]]] = [
    (cat, [re.compile(r'\b' + re.escape(kw) + r'\b') for kw in kws])
    for cat, kws in _FALLBACK_RULES
]


def assign_category(label: str) -> str:
    """Map a CLIP label to one of 6 semantic categories.

    Lookup order:
    1. Supplementary vocab explicit map (_SUPP_MAP) — deterministic for all
       labels in clip_labeler._PATCH_VOCAB and _TEXTURE_SCENE_VOCAB.
    2. ImageNet-1000 class name → 'object'. Handles compound names like
       'black bear' or 'water buffalo' that would otherwise misfire on
       color/scene keywords.
    3. Keyword fallback — safety net for novel label strings not in the
       vocabulary (should not occur for clip_labeler output).
    4. Default → 'object'.
    """
    label_lower = label.lower()

    if label_lower in _SUPP_MAP:
        return _SUPP_MAP[label_lower]

    if label_lower in _IMAGENET_CLASSES:
        return 'object'

    for category, patterns in _FALLBACK_PATTERNS:
        if any(p.search(label_lower) for p in patterns):
            return category

    return 'object'


def get_category_distribution(labels: list) -> dict:
    """Count features per category for a list of label strings."""
    dist = {cat: 0 for cat in CATEGORIES}
    for label in labels:
        dist[assign_category(label)] += 1
    return dist
